git:
  depth: false
  quiet: true

language: python
  - "3.7"

services:
  - docker

before_install:
  - docker run -d -p 5672:5672 --name rabbit rabbitmq:3-management
  - docker build -t job_consumer ./task_executor
  - docker run -d --network host job_consumer job_queue -to 2

install:
  - cd task_management_project
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate 

script:
  - python -m pytest --liveserver 127.0.0.1:8000
