# Generated by Django 3.1.2 on 2020-10-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('job_status', models.CharField(choices=[('CR', 'Created'), ('ST', 'Started'), ('RS', 'Rtarted'), ('DL', 'Deleted'), ('CN', 'Cancelled')], default='CR', max_length=2)),
            ],
        ),
    ]
