# Generated by Django 3.1.2 on 2020-10-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20201027_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('CR', 'Created'), ('ST', 'Started'), ('RS', 'Restarted'), ('DL', 'Deleted'), ('CN', 'Cancelled'), ('EN', 'Ended')], default='CR', max_length=2),
        ),
    ]
