# Generated by Django 3.1.2 on 2020-10-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_auto_20201028_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sleep_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
