name: Test Django Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Run the rabbitmq docker container
      run: |
        docker run -d -p 5672:5672 --name rabbit rabbitmq:3-management
    - name: Build the docker image (job_consumer)
      run: |
        docker build -t job_consumer ./task_executor
    - name: Run the docker container job_consumer
      run: |
        docker run -d --network host job_consumer job_queue -to 2
    - name: Install dependencies
      working-directory: ./task_management_project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py makemigrations
        python manage.py migrate
    - name: Run tests
      working-directory: ./task_management_project
      run: python -m pytest --liveserver 127.0.0.1:8000
